---
name: Update LOLAPPS-Project.github.io
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - uses: actions/checkout@v2
      - name: Convert Desktop_App and Web_App .yml to .md
        run: |
          # Ensure target directories exist
          mkdir -p _lolapps/Desktop
          mkdir -p _lolapps/Web

          # Convert Desktop_App .yml files to .md and move to _lolapps/Desktop
          for file in yml/Desktop_App/*.yml; do
            new_file="_lolapps/Desktop/$(basename "${file/%\.yml/.md}")"
            mv "$file" "$new_file"  # Convert and move
          done

          # Convert Web_App .yml files to .md and move to _lolapps/Web
          for file in yml/Web_App/*.yml; do
            new_file="_lolapps/Web/$(basename "${file/%\.yml/.md}")"
            mv "$file" "$new_file"
          done

      - name: Deploy to LOLAPPS-Project.github.io repo
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.REPO_WRITE }}
          external_repository: LOLAPPS-Project/lolapps-project.github.io
          publish_branch: master
          publish_dir: _lolapps
          enable_jekyll: true
          keep_files: false
          commit_message: "Applying update"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
