---
name: PUSH & PULL REQUEST - YAML Lint and Schema Validation Checks
on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lintFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          no_warnings: true
          file_or_dir: yml/**/*.yml
          config_file: .github/.yamllint
      - name: Validate Template Schema
        uses: cketti/action-pykwalify@v0.3-temp-fix
        with:
          files: YML-Template.yml
          schema: YML-Schema.yml
      - name: Validate Desktop YAML Schema
        uses: cketti/action-pykwalify@v0.3-temp-fix
        with:
          files: yml/Desktop_App/*.yml
          schema: YML-Schema.yml
      - name: Validate Web YAML Schema
        uses: cketti/action-pykwalify@v0.3-temp-fix
        with:
          files: yml/Web_App/*.yml
          schema: YML-Schema.yml
# Commenting out until mobile becomes a thing.
#      - name: Validate Mobile YAML Schema
#        uses: cketti/action-pykwalify@v0.3-temp-fix
#        with:
#          files: yml/Mobile/*.yml
#          schema: YML-Schema.yml
